## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('applications', ['internet', 'config-store','stats'])
    module.source = [
        # 'model/bloom-filter.cc',
				'model/transaction.cc',
				'model/dash.cc',
				'model/dash-node.cc',
				'model/dash-miner.cc',
				'helper/dash-topology-helper.cc',
				'helper/dash-node-helper.cc',
				'helper/dash-miner-helper.cc',
#				'model/dash-simple-attacker.cc',
#				'model/dash-selfish-miner.cc',
#				'model/dash-selfish-miner-trials.cc',
        'model/bulk-send-application.cc',
        'model/onoff-application.cc',
        'model/packet-sink.cc',
        'model/udp-client.cc',
        'model/udp-server.cc',
        'model/seq-ts-header.cc',
        'model/udp-trace-client.cc',
        'model/packet-loss-counter.cc',
        'model/udp-echo-client.cc',
        'model/udp-echo-server.cc',
        'model/application-packet-probe.cc',
        'helper/bulk-send-helper.cc',
        'helper/on-off-helper.cc',
        'helper/packet-sink-helper.cc',
        'helper/udp-client-server-helper.cc',
        'helper/udp-echo-helper.cc',
        ]

    applications_test = bld.create_ns3_module_test_library('applications')
    applications_test.source = [
        'test/udp-client-server-test.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'applications'
    headers.source = [
        # 'model/bloom-filter.h',
        # 'model/MurmurHash3.h',
				'model/transaction.h',
				'model/uint256.h',
				'model/prevector.h',
				'model/serialize.h',
				'model/version.h',
				'model/byteswap.h',
				'model/endian.h',
				'model/sanity.h',
				'model/common.h',
				'model/dash.h',
				'model/dash-node.h',
				'model/dash-miner.h',
				'helper/dash-topology-helper.h',
				'helper/dash-node-helper.h',
				'helper/dash-miner-helper.h',
        'model/bulk-send-application.h',
        'model/onoff-application.h',
        'model/packet-sink.h',
        'model/udp-client.h',
        'model/udp-server.h',
        'model/seq-ts-header.h',
        'model/udp-trace-client.h',
        'model/packet-loss-counter.h',
        'model/udp-echo-client.h',
        'model/udp-echo-server.h',
        'model/application-packet-probe.h',
        'helper/bulk-send-helper.h',
        'helper/on-off-helper.h',
        'helper/packet-sink-helper.h',
        'helper/udp-client-server-helper.h',
        'helper/udp-echo-helper.h',
        ]

    bld.ns3_python_bindings()
